version: '3.8'
services:
    postgres:
        image: postgres:latest
        ports:
            - "35000:5432"
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: base

    api:
        # image: be-base
        build:
            dockerfile: Dockerfile
            context: .
        depends_on:
            - postgres
        environment:
            DATABASE_URL: postgres://postgres:postgres@postgres:5432/base
            NODE_ENV: development
            PORT: 3000
        ports:
            - "8000:3000"
    
  